name: Create Releases for Microservices

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          curl -sSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: |
          gh auth login --with-token < "${GITHUB_TOKEN}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Repository List
        run: |
          TARGET_REPOSITORIES=$(cat repositories.txt)
          echo "Target Repositories: $TARGET_REPOSITORIES"
        shell: bash

      - name: Create Releases
        run: |
          ORGANIZATION="m3rryqold"
          for repo in $TARGET_REPOSITORIES; do
            echo "Creating release for $repo"
            gh release create "$ORGANIZATION/$repo" --title "Release for $repo" --notes "Release notes for $repo"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
