name: Create Releases for Microservices

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read Repository List
        run: |
          TARGET_REPOSITORIES=$(cat repositories.txt)
          echo "Target Repositories: $TARGET_REPOSITORIES"
        shell: bash

      - name: Create Releases
        run: |
          ORGANIZATION="your-organization"
          for repo in $TARGET_REPOSITORIES; do
            echo "Creating release for $repo"
            gh release create "$ORGANIZATION/$repo" --title "Release for $repo" --notes "Release notes for $repo"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
